### ISSUE TITLE
Assertion Failed! WebCard on FirefoxESR under Windows 10

### ISSUE THREAD

**Issue by Shineryc** [cardid/WebCard-IE#14]
Hi @cheburashka, i have installed WebCard on Firefox ESR, it's worked, but sometimes it's returned error when i'm moving from one page to another.
![image](https://user-images.githubusercontent.com/29034635/39120172-e75d0090-4717-11e8-9827-9f37c057a3bc.png)
any solution?
i have rebuilded again the project, but still same..
thanks

**Comment by adricasti** [comment]
That seem to be caused in the upstream [FireBreath](https://github.com/Firebreath) framework, you may want to raise the question there. Out of curiosity @Shineryc, in what site are you using WebCard and for what use?

**Comment by Shineryc** [comment]
it's solved, using your msi installer. i'm creting project web login page using smartcard.

**Comment by Shineryc** [comment]
it,s still under development..

**Comment by changuna** [comment]
Hi Shineryc,

Good work.
Please provide me with your solution.
Thanks a lot

Best Regards

Chan Gunawardena

**Comment by Shineryc** [comment]
Hi changuna,
Sorry for late response

as far as i know, modern browser doesn't support any plugin anymore, but if you still want to use this project, you can use Firefox ESR(Extended Support Release). 
you can rebuild again the project or just install from the msi installer that provided in the project page.
