### ISSUE TITLE
Provide code nextapdu

### ISSUE THREAD

**Issue by pbellede** [cardid/WebCard-IE#4]
Hello,

Please could you provide code for nextapdu to provide card type

on 

url: WebCard.remoteURL + "/nextapdu",

Thanks a lot

**Comment by adricasti** [comment]
Hi pbellede, the server part of http://plugin.cardid.org is currently free (as in free speech) and you can use it without restrictions. It is not however free (as in free beer) but if you let me know more about your use case I could probably add functionality to the server API to cater for your requirement.

**Comment by pbellede** [comment]
Hello,

Thanks a lot, could you provide source code of nextapdu

**Comment by pbellede** [comment]
Thank you for your great work
