### ISSUE TITLE
Chrome Support NPAPI

### ISSUE THREAD

**Issue by pbellede** [cardid/WebCard-IE#5]
Hello,

Chrome NPAPI plugin was not supported, could you have an idea to support PPAPI

Thanks a lot.

**Comment by nuruzzaman** [comment]
As of Chrome Version 42, an additional configuration step is required to continue using NPAPI plugins.
In your URL bar write-->  
1. chrome://flags/#enable-npapi 
2. Click the Enable link for the Enable NPAPI configuration option.
3. Click the Relaunch button that now appears at the bottom of the configuration page.

**Comment by pbellede** [comment]
Ok but for future Chrome Version support was disable.

**Comment by nuruzzaman** [comment]
If i can arrange free time, I have a plan to work on this PPAPI plug-ins. Please also share with me if you have one.  Thanks a lot.

**Comment by pbellede** [comment]
i will pay a beer

**Comment by nuruzzaman** [comment]
thanks in advance... lets work together to achieve it. Add into your Skype ID: dr.zaman1981

**Comment by adricasti** [comment]
Thanks guys, as you know, Chrome has dropped support for NPAPI plugins. The FireBreath framework that WebCard is based on seems to provide a way to implement a solution through the use of native messaging, but I've had no time to implement it. 

If anyone wants to give it a try, I'm happy to assist if I can and incorporate contributions.

**Comment by ghost** [comment]
How far is this project in supporting PPAPI or another API that works after NPAPI died?

Maybe, this is an opportunity to set up a crowdfunding or other effort to get more funding to get this done, maybe reach out to other open-source projects to jump in. I think it is a shame no PGP Card extensions are out there now. Please re-open.
