### ISSUE TITLE
How to check if the card present in reader when page load?

### ISSUE THREAD

**Issue by mahrous78** [cardid/WebCard-IE#6]
Hey,
How to check if the card is already present in the reader when page load?

Thanks

**Comment by adricasti** [comment]
I would suggest you iterate through `WebCard.readers` to check the `state` property., it returns the underlying [SCARD_READERSTATE](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379808%28v=vs.85%29.aspx). You can check winscard.h from the Windows SDK for the constant numeric values.
