### ISSUE TITLE
WeakHost Expired.

### ISSUE THREAD

**Issue by ofumbi** [cardid/WebCard-IE#7]
when I build debug version in VS 2012, I get an error as I try to reload the test page. NPP.cpp Line 232. Expression weakHost.Expired() could this indicate a memory leak?

**Comment by adricasti** [comment]
Thanks for this report. Probably, but I think the NPP.cpp file you mention is part of the FireBreath framework so I would suggest you raise the issue to the [Firebreath team](http://jira.firebreath.org/secure/Dashboard.jspa)
