### ISSUE TITLE
t0 or t1

### ISSUE THREAD

**Issue by andreypapp** [cardid/WebCard-IE#8]
is there any chance of getting/setting the protocol? (T=0 or T=1). The card i am trying to work with accepts commands in both protocols (low-level in t=0 and applet-based in t=1)

Thanks in advance.

**Comment by adricasti** [comment]
Currently, the call to [SCardConnect](https://github.com/cardid/WebCard/blob/master/Reader.cpp#L7) lets the driver select the appropriate protocol. I have not seen cards that support both, so normally a card that supports T=1 will use it and if not it will fall back to T=0. You could change the code to explicitly state the protocol you want to use in that line.
