### ISSUE TITLE
Plugin does not work on modern browsers?

### ISSUE THREAD

**Issue by nitzanb** [cardid/WebCard-IE#9]
Not sure if this is a bug or issue with new browser version, but I can only use this plugin with internet explorer 11. It does not run in edge nor chrome. (Running windows 10).

I've tested that on two different computers with the same result each time.

**Comment by adricasti** [comment]
Correct, modern browsers do not support old style ActiveX or NPAPI. Please comment on [Issue #5](https://github.com/cardid/WebCard/issues/5) if you want to contribute funding or pull requests to make a Chrome Extension.
